services:
  auth-service:
    build: ./auth
    ports:
      - "3003:3003"

  catalogo-service:
    build: ./catalogo
    ports:
      - "3001:3001"

  carrinho-service:
    build: ./carrinho
    ports:
      - "3002:3002"

  pedidos-service:
    build: ./pedidos
    ports:
      - "3004:3004"